[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
    'npm ci --include=dev',
    'ls -la node_modules/.bin | head -10'
]

[phases.build]
cmds = [
    'npm run build',
    'ls -la dist/'
]

[start]
cmd = 'npm run start'